language: csharp
sudo: required  
dist: trusty  
mono: latest

script:
  - msbuild /p:Configuration=Release DocumentReaderService.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./DocumentReaderService.Tests/bin/Release/DocumentReaderService.Tests.dll